import React from 'react';
import {Container, Row, Col} from 'react-bootstrap';


class Language extends React.Component{
    render(){
        return(
            <div class='container about'>
            <Container>
                <Row>
                <Col md={3} className='serviceHeader'><b>Language Transcription</b>
                    <hr style={{
                        'width': '30%'
                    }}></hr>
                </Col>
                <Col md={9}>
                    <b className='subHeader'>
                    Sentiment analysis
                    </b>
                    <br></br>
                    <p className='description'>
                        The team does sentiment analysis for variety of solutions ranging from systems that focus on polarity (positive, negative, neutral) to systems that detect feelings and emotions (angry, happy, sad, etc) or identify intentions (e.g. interested, not interested)
                    </p>
                    <b className='subHeader'>
                        Document Comprehension
                    </b>
                    <br></br>
                    <p className='description'>
                        Our team can help you get the answers of important questions from a big textual document.
                    </p>
                    <b className='subHeader'>
                        Digitisation
                    </b>
                    <br></br>
                    <p className='description'>
                        We take all kinds of handwritten data ranging from customers feedback to doctors prescriptions and digitise them.
                    </p>
                    <b className='subHeader'>
                        OCR validation
                    </b>
                    <br></br>
                    <p className='description'>
                        We validate and correct the output generated by OCR systems to make it cent percent accurate.
                    </p>
                    <b className='subHeader'>
                        Content Filtering
                    </b>
                    <br></br>
                    <p className='description'>
                        Be it inappropriate tweets or comments, our team can curate all objectional content helping you make you site cleaner and better.
                    </p>
                    <b className='subHeader'>
                        Customer Support
                    </b>
                    <br></br>
                    <p className='description'>
                        Our team can help you provide customer care for all kinds of products.
                    </p>
                    <b className='subHeader'>
                        Translation
                    </b>
                    <br></br>
                    <p className='description'>
                        We do quality data translations from English to Hindi and vice versa.
                    </p>

                </Col>
        </Row>
        </Container>
        </div>
        );
    }
}

export default Language;