import React from 'react';
import {Container, Row, Col} from 'react-bootstrap';


class Language extends React.Component{
    render(){
        return(
            <div class='container about'>
            <Container>
                <Row>
                <Col md={3} className='serviceHeader'><b>Language Transcription</b>
                                <hr style={{
                                    'width': '30%'
                                }}></hr>
                            </Col>
                            <Col md={9}>
                               
                                <b className='subHeader'>
                                Sentiment analysis 
                                </b>
                                <br></br>
                                <p className='description'>The team does sentiment analysis for variety of solutions ranging from systems that focus on polarity (positive, negative, neutral) to systems that detect feelings and emotions (angry, happy, sad, etc) or identify intentions (e.g. interested, not interested)

                                </p>

                                <b className='subHeader'>
                                OCR validation
                                </b>
                                <br></br>
                                <p className='description'>We validate and correct the output generated by OCR systems to make it cent percent accurate.
.</p>
                                <b className='subHeader'>
                                Digitisation
                                </b>
                                <br></br>
                                <p className='description'>We take all kinds of handwritten data ranging from customers feedback to doctors prescriptions and digitise them.
                                </p>
                            </Col>
                    </Row>
                    </Container>
                    </div>
        );
    }
}

export default Language;